#!/bin/sh
set -e
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable github-downloader-web.service
    systemctl start github-downloader-web.service || true
fi
exit 0